<table>
    <tr>
        <td>
            <div align ="center">
                <font color="orange" size=8px>
                    <b> NLP Project on <br> Flipkart reviews sentiment Analysis
                    </b>
                </font>
            </div>
        </td>
    <tr>
<table>

### <font color=orange> Problem Statement </font> :  

Analysing Customer's choice for Flipkart based on the reviews and ratings. 

Evaluation of an individual's sentiment from a piece of text is challenging.

Sentiment analysis is necessary to get customer feelings,attitudes, reactions, and opinions of existing and potential buyers towards flipkart's products or services.

So lets apply the NLP techniques to analyze the customer reviews in Flipkart.

# Flipkart Electronics reviews Web scrapped Data

##### Importing required libraries

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline

### Product 1 : wired headset

In [2]:
df=pd.DataFrame()
for i in range(1,520):
    url='https://www.flipkart.com/redmi-mi-hi-resolution-audio-wired-headset/product-reviews/itmfc704fbf24f2c?pid=ACCFUT9HGEZ5XNKZ&lid=LSTACCFUT9HGEZ5XNKZLFX2ZK&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df=df.append(temp, ignore_index=True)
        
df[['review_title','review','rate','category']]
df['rating']=df['rate'].str.extract('(\d+)')

df.head()

,category,rate,review,review_title,rating
0,redmi-mi-hi-resolution-audio-wired-headset,2Slightly disappointed,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,redmi-mi-hi-resolution-audio-wired-headset,5Great product,Very good product and sound quality is very ni...,Great product,5
2,redmi-mi-hi-resolution-audio-wired-headset,5Must buy!,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,redmi-mi-hi-resolution-audio-wired-headset,4Good choice,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,redmi-mi-hi-resolution-audio-wired-headset,4Delightful,"Though I have received it today, they were run...",Delightful,4

In [3]:
df.shape

(4997, 5)

In [4]:
df.head()

,category,rate,review,review_title,rating
0,redmi-mi-hi-resolution-audio-wired-headset,2Slightly disappointed,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,redmi-mi-hi-resolution-audio-wired-headset,5Great product,Very good product and sound quality is very ni...,Great product,5
2,redmi-mi-hi-resolution-audio-wired-headset,5Must buy!,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,redmi-mi-hi-resolution-audio-wired-headset,4Good choice,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,redmi-mi-hi-resolution-audio-wired-headset,4Delightful,"Though I have received it today, they were run...",Delightful,4

### Product 2: Power Bank

In [5]:
df1=pd.DataFrame()
for i in range(1,783):  #number of review pages for this product=782
    url='https://www.flipkart.com/mi-3i-20000-mah-power-bank-fast-charging-18w/product-reviews/itmff9ed1f750abc?pid=PWBFVGXXFGEBYRF5&lid=LSTPWBFVGXXFGEBYRF514LSY9&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df1=df1.append(temp, ignore_index=True)
        
df1[['review_title','review','rate','category']]
df1['rating']=df1['rate'].str.extract('(\d+)')  #extracting only numeric value for rating from rate column

df1.head()

,category,rate,review,review_title,rating
0,mi-3i-20000-mah-power-bank-fast-charging-18w,4Good quality product,* best battery life * good performance* value ...,Good quality product,4
1,mi-3i-20000-mah-power-bank-fast-charging-18w,5Fabulous!,Best power and fast charging i love this produ...,Fabulous!,5
2,mi-3i-20000-mah-power-bank-fast-charging-18w,4Nice product,Pros: 1.Charging time with 18W charger is 7 ho...,Nice product,4
3,mi-3i-20000-mah-power-bank-fast-charging-18w,5Super!,Good product 20000mAh power bank. And original...,Super!,5
4,mi-3i-20000-mah-power-bank-fast-charging-18w,5Must buy!,Thank you so much Flipkart this is a great pow...,Must buy!,5

In [6]:
print(df1.shape)

(7507, 5)

In [7]:
a1=pd.concat([df,df1],ignore_index=True) #combining the two dataframes
print(a1.shape)
a1.head()

(12504, 5)

,category,rate,review,review_title,rating
0,redmi-mi-hi-resolution-audio-wired-headset,2Slightly disappointed,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,redmi-mi-hi-resolution-audio-wired-headset,5Great product,Very good product and sound quality is very ni...,Great product,5
2,redmi-mi-hi-resolution-audio-wired-headset,5Must buy!,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,redmi-mi-hi-resolution-audio-wired-headset,4Good choice,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,redmi-mi-hi-resolution-audio-wired-headset,4Delightful,"Though I have received it today, they were run...",Delightful,4

### Product 3: Apple watch

In [8]:
df2=pd.DataFrame()
for i in range(1,387):  
    url='https://www.flipkart.com/apple-watch-series-3-gps-42-mm-space-grey-aluminium-case-black-sport-band/product-reviews/itm91c560e722cdd?pid=SMWF94AYMNYHTYDJ&lid=LSTSMWF94AYMNYHTYDJU9ZHY3&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df2=df2.append(temp, ignore_index=True)
        
df2[['review_title','review','rate','category']]
df2['rating']=df2['rate'].str.extract('(\d+)')

df2.head()

,category,rate,review,review_title,rating
0,apple-watch-series-3-gps-42-mm-space-grey-alum...,5Perfect product!,Thank you for delivery it just in one day . I ...,Perfect product!,5
1,apple-watch-series-3-gps-42-mm-space-grey-alum...,5Classy product,"Superb Quality , Nothing like apple , No need ...",Classy product,5
2,apple-watch-series-3-gps-42-mm-space-grey-alum...,5Classy product,Apple does seem to release stable product over...,Classy product,5
3,apple-watch-series-3-gps-42-mm-space-grey-alum...,5Terrific,My First Apple Watch!!! Simply Amazing.I used ...,Terrific,5
4,apple-watch-series-3-gps-42-mm-space-grey-alum...,5Terrific purchase,Seriously I can‚Äôt express my inner feelings......,Terrific purchase,5

In [9]:
df2.shape

(3854, 5)

In [10]:
a2=pd.concat([a1,df2],ignore_index=True)
print(a2.shape)
#a2.head()

(16358, 5)

### Product 4: Mobile Holder

In [11]:
df3=pd.DataFrame()
for i in range(1,438):  
    url='https://www.flipkart.com/portronics-por-122-modesk-universal-mobile-holder-black/product-reviews/itmfdbm8axuvkey6?pid=MOHFDB7TUX5VHBMW&lid=LSTMOHFDB7TUX5VHBMWTRRZHM&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df3=df3.append(temp, ignore_index=True)
        
df3[['review_title','review','rate','category']]
df3['rating']=df3['rate'].str.extract('(\d+)')

df3.head()

,category,rate,review,review_title,rating
0,portronics-por-122-modesk-universal-mobile-hol...,5Classy product,Good quality product by this companyThe build ...,Classy product,5
1,portronics-por-122-modesk-universal-mobile-hol...,5Best in the market!,Good product. Made up of good metal. Have a ni...,Best in the market!,5
2,portronics-por-122-modesk-universal-mobile-hol...,3Decent product,Product quality is good but it should be give ...,Decent product,3
3,portronics-por-122-modesk-universal-mobile-hol...,5Terrific purchase,Perfect product. At a good price. Sturdy build...,Terrific purchase,5
4,portronics-por-122-modesk-universal-mobile-hol...,5Brilliant,"Excellent finish, sturdy, correctly weighted t...",Brilliant,5

In [12]:
df3.shape

(4144, 5)

In [13]:
a3=pd.concat([a2,df3],ignore_index=True)
print(a3.shape)

(20502, 5)

### Product 5: BP Monitor

In [14]:
df4=pd.DataFrame()
for i in range(1,314):  
    url='https://www.flipkart.com/omron-hem-7124-bp-monitor/product-reviews/itmeh7sqdjzuuw9h?pid=BPMEH7SQU5GDJZHS&lid=LSTBPMEH7SQU5GDJZHSOVTPUB&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df4=df4.append(temp, ignore_index=True)
        
df4[['review_title','review','rate','category']]
df4['rating']=df4['rate'].str.extract('(\d+)')

df4.head()

,category,rate,review,review_title,rating
0,omron-hem-7124-bp-monitor,5Worth every penny,nice packaging and this dp monitor are very us...,Worth every penny,5
1,omron-hem-7124-bp-monitor,4Pretty good,Received the product today. In absolutely good...,Pretty good,4
2,omron-hem-7124-bp-monitor,5Awesome,good one with good and almost accurate reading...,Awesome,5
3,omron-hem-7124-bp-monitor,4Very Good,overall good but u have to check bp 2 times in...,Very Good,4
4,omron-hem-7124-bp-monitor,5Great product,Amazing Delivery at such a Lockdown time...Rea...,Great product,5

In [15]:
df4.shape

(3120, 5)

In [16]:
a4=pd.concat([a3,df4],ignore_index=True)
print(a4.shape)

(23622, 5)

### Product 6: External hard disk

In [17]:
df5=pd.DataFrame()
for i in range(1,319):  
    url='https://www.flipkart.com/seagate-backup-plus-slim-1-tb-external-hard-disk-drive/product-reviews/itmffueqescquj7f?pid=ACCFFUEQQHZHTUCB&lid=LSTACCFFUEQQHZHTUCBMHXW6Q&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df5=df5.append(temp, ignore_index=True)
        
df5[['review_title','review','rate','category']]
df5['rating']=df5['rate'].str.extract('(\d+)')

df5.head()

,category,rate,review,review_title,rating
0,seagate-backup-plus-slim-1-tb-external-hard-di...,5Wonderful,I have been using this since the last 3 weeks....,Wonderful,5
1,seagate-backup-plus-slim-1-tb-external-hard-di...,5Awesome,Wonderful product... best in this price range....,Awesome,5
2,seagate-backup-plus-slim-1-tb-external-hard-di...,3Does the job,Light weight and handy one.....with 1.8 tb of ...,Does the job,3
3,seagate-backup-plus-slim-1-tb-external-hard-di...,5Best in the market!,very Satisfied with the product. Speed is good...,Best in the market!,5
4,seagate-backup-plus-slim-1-tb-external-hard-di...,1Not recommended at all,This hard disk has been became defective once ...,Not recommended at all,1

In [18]:
df5.shape

(3154, 5)

In [19]:
a5=pd.concat([a4,df5],ignore_index=True)
print(a5.shape)

(26776, 5)

### Product 7: Wired mouse

In [20]:
df6=pd.DataFrame()
for i in range(1,524):  
    url='https://www.flipkart.com/dell-ms-116-wired-optical-mouse/product-reviews/itmekm2ggehfhfaw?pid=ACCEKM2GZAGFW2TM&lid=LSTACCEKM2GZAGFW2TMF3S8CR&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df6=df6.append(temp, ignore_index=True)
        
df6[['review_title','review','rate','category']]

df6['rating']=df6['rate'].str.extract('(\d+)')

df6.head()

,category,rate,review,review_title,rating
0,dell-ms-116-wired-optical-mouse,5Worth every penny,Bestest wired (üêÅ ) mouse everPoints1. I like i...,Worth every penny,5
1,dell-ms-116-wired-optical-mouse,5Brilliant,"Original StuffSuperb Classic Design, Best Touc...",Brilliant,5
2,dell-ms-116-wired-optical-mouse,5Super!,Nice product received from Dell...Dell is one ...,Super!,5
3,dell-ms-116-wired-optical-mouse,5Worth every penny,Decent mouse with smooth movement..Nothing els...,Worth every penny,5
4,dell-ms-116-wired-optical-mouse,5Perfect product!,"Easy to use, the performance is good , it is c...",Perfect product!,5

In [21]:
df6.shape

(5142, 5)

In [22]:
a6=pd.concat([a5,df6],ignore_index=True)
print(a6.shape)

(31918, 5)

### Product 8: Printer

In [23]:
df7=pd.DataFrame()
for i in range(1,204):  
    url='https://www.flipkart.com/epson-l3110-multi-function-color-printer/product-reviews/itmfb28z2g9ygubg?pid=PRNFB28YS326QDZF&lid=LSTPRNFB28YS326QDZF5KC7M2&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df7=df7.append(temp, ignore_index=True)
        
df7[['review_title','review','rate','category']]
df7['rating']=df7['rate'].str.extract('(\d+)')

df7.head()

,category,rate,review,review_title,rating
0,epson-l3110-multi-function-color-printer,5Must buy!,Great printer. The color reproduction on the p...,Must buy!,5
1,epson-l3110-multi-function-color-printer,4Wonderful,good priinter at the pricebut as i expect ink ...,Wonderful,4
2,epson-l3110-multi-function-color-printer,1Very poor,Not a very user friendly printer..Canon in thi...,Very poor,1
3,epson-l3110-multi-function-color-printer,5Brilliant,It is very good Products and its printing qual...,Brilliant,5
4,epson-l3110-multi-function-color-printer,4Nice product,printer works very well.. great quality... per...,Nice product,4

In [24]:
df7.shape

(2011, 5)

In [25]:
a7=pd.concat([a6,df7],ignore_index=True)
print(a7.shape)

(33929, 5)

### Product 9: Digital Weighing Scale

In [26]:
df8=pd.DataFrame()
for i in range(1,668):  
    url='https://www.flipkart.com/dr-trust-usa-executive-rechargeable-digital-weighing-scale-electronic-weight-machine-human-body-temperature-display-usb-cable-included/product-reviews/itm23f04b83d31ee?pid=WSLF63F5AYBDEEGJ&lid=LSTWSLF63F5AYBDEEGJULFQKJ&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df8=df8.append(temp, ignore_index=True)
        
df8[['review_title','review','rate','category']]
df8['rating']=df8['rate'].str.extract('(\d+)')

df8.head()

,category,rate,review,review_title,rating
0,dr-trust-usa-executive-rechargeable-digital-we...,1Utterly Disappointed,It's not good please don't go for it.. Weighin...,Utterly Disappointed,1
1,dr-trust-usa-executive-rechargeable-digital-we...,5Just wow!,I got this weight machine on April 25. The bui...,Just wow!,5
2,dr-trust-usa-executive-rechargeable-digital-we...,1Worthless,"Waste of money, time and energyThe machine wor...",Worthless,1
3,dr-trust-usa-executive-rechargeable-digital-we...,5Awesome,"Excellent product , received it in very good c...",Awesome,5
4,dr-trust-usa-executive-rechargeable-digital-we...,4Delightful,My first product is rip in just 3 week. But th...,Delightful,4

In [27]:
df8.shape

(6588, 5)

In [28]:
a8=pd.concat([a7,df8],ignore_index=True)
print(a8.shape)

(40517, 5)

### Product 10: Pendrive

In [29]:
df9=pd.DataFrame()
for i in range(1,668):  
    url='https://www.flipkart.com/sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-pen-drive/product-reviews/itmf3qyaaqr5azmn?pid=ACCDZ583WDDSDY3F&lid=LSTACCDZ583WDDSDY3F3ITXX5&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df9=df9.append(temp, ignore_index=True)
        
df9[['review_title','review','rate','category']]
df9['rating']=df9['rate'].str.extract('(\d+)')

df9.head()

,category,rate,review,review_title,rating
0,sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-...,5Simply awesome,SanDisk is a nice brand...64gb pendrive i have...,Simply awesome,5
1,sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-...,4Pretty good,After a day of use reading fast writing speed ...,Pretty good,4
2,sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-...,5Perfect product!,It was good .EVEN DELIVERY EXPERIENCE WAS ALSO...,Perfect product!,5
3,sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-...,2Not good,I bought this pendrive for my VU TV but it's n...,Not good,2
4,sandisk-sdcz50-064g-i35-sdcz50-064g-b35-64-gb-...,5Value for money..,Best in the price range compared to other bran...,Value for money..,5

In [30]:
df9.shape

(6566, 5)

In [31]:
a9=pd.concat([a8,df9],ignore_index=True)
print(a9.shape)

(47083, 5)

### Product 11: Camera

In [32]:
df10=pd.DataFrame()
for i in range(1,337):  
    url='https://www.flipkart.com/canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens/product-reviews/itm6f665fea97bc2?pid=CAMF3DHJURPEMNRN&lid=LSTCAMF3DHJURPEMNRNYD4BKP&marketplace=FLIPKART&page={}'.format(i)
    category=url.split('/')[3]
    HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})
    
    data = requests.get(url,headers=HEADERS)
    soup = BeautifulSoup(data.content)
    category=url.split('/')[3]
    parent_tags=soup.findAll('div',{'class':'col _2wzgFH K0kLPL'})
    
    for parent in parent_tags:
        try:
            review_headline=parent.find('p',{'class':'_2-N8zT'}).text
        except:
            review_headline=None
        try:
            review=parent.find('div',{'class':'t-ZTKy'}).text
        except:
            review=None
        try:
            rate=parent.select_one('div',{'class':'_3LWZlK _1BLPMq','class':'_3LWZlK _1rdVr6 _1BLPMq'}).text
                
        except:
            rate=None
    
        temp={
        'review_title':review_headline,
        'review':review,
        'rate':rate,
        'category':category}
        
        df10=df10.append(temp, ignore_index=True)
        
df10[['review_title','review','rate','category']]
df10['rating']=df10['rate'].str.extract('(\d+)')

df10.head()

,category,rate,review,review_title,rating
0,canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens,5Excellent,product really great . I am totally sctified t...,Excellent,5
1,canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens,3Does the job,Satisfied with the product.. Its a really good...,Does the job,3
2,canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens,4Worth the money,The camera simply awesome..and it is a best bu...,Worth the money,4
3,canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens,5Just wow!,Worth more than the amount. Best DSLR for a go...,Just wow!,5
4,canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens,5Best in the market!,"product is very good and build quality also , ...",Best in the market!,5

In [33]:
df10.shape

(3352, 5)

In [34]:
a10=pd.concat([a9,df10],ignore_index=True)
print(a10.shape)

(50435, 5)

In [35]:
rev=a10.copy()

In [36]:
rev.head()

,category,rate,review,review_title,rating
0,redmi-mi-hi-resolution-audio-wired-headset,2Slightly disappointed,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,redmi-mi-hi-resolution-audio-wired-headset,5Great product,Very good product and sound quality is very ni...,Great product,5
2,redmi-mi-hi-resolution-audio-wired-headset,5Must buy!,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,redmi-mi-hi-resolution-audio-wired-headset,4Good choice,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,redmi-mi-hi-resolution-audio-wired-headset,4Delightful,"Though I have received it today, they were run...",Delightful,4

In [37]:
rev.shape

(50435, 5)

In [38]:
rev=rev.drop('rate',axis=1)

In [39]:
rev.head()

,category,review,review_title,rating
0,redmi-mi-hi-resolution-audio-wired-headset,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,redmi-mi-hi-resolution-audio-wired-headset,Very good product and sound quality is very ni...,Great product,5
2,redmi-mi-hi-resolution-audio-wired-headset,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,redmi-mi-hi-resolution-audio-wired-headset,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,redmi-mi-hi-resolution-audio-wired-headset,"Though I have received it today, they were run...",Delightful,4

In [40]:
rev.shape

(50435, 4)

In [41]:
rev.to_csv('flipkart_reviews.csv') #converting dataframe to csv file

In [43]:
fp=pd.read_csv('flipkart_reviews.csv')  #loading and checking the csv file
fp.head()

,Unnamed: 0,category,review,review_title,rating
0,0,redmi-mi-hi-resolution-audio-wired-headset,Kinda good with great sound effects three diff...,Slightly disappointed,2
1,1,redmi-mi-hi-resolution-audio-wired-headset,Very good product and sound quality is very ni...,Great product,5
2,2,redmi-mi-hi-resolution-audio-wired-headset,Redmi Earphones is the best earphones I have u...,Must buy!,5
3,3,redmi-mi-hi-resolution-audio-wired-headset,Red colour looks stunning üòç.Sound quality is c...,Good choice,4
4,4,redmi-mi-hi-resolution-audio-wired-headset,"Though I have received it today, they were run...",Delightful,4